"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
exports.__esModule = true;
var body_parser_1 = __importDefault(require("body-parser"));
var express_1 = __importDefault(require("express"));
var express_flash_1 = __importDefault(require("express-flash"));
var morgan_1 = __importDefault(require("morgan"));
var passport_1 = __importDefault(require("passport"));
var path_1 = __importDefault(require("path"));
var Passport_1 = require("./Config/Passport");
var Session_1 = require("./Config/Session");
var RoomController_1 = require("./Controllers/RoomController");
var UserController_1 = require("./Controllers/UserController");
var UserService_1 = require("./Services/UserService");
exports.app = express_1["default"]();
exports.app.set("views", path_1["default"].join(__dirname, "Views"));
exports.app.set("view engine", "ejs");
exports.app.set("query parser", "simple");
exports.app.use(body_parser_1["default"].json());
exports.app.use(body_parser_1["default"].urlencoded({ extended: true }));
exports.app.use(Session_1.sessionMiddleware);
exports.app.use(passport_1["default"].initialize());
exports.app.use(passport_1["default"].session());
exports.app.use(express_flash_1["default"]());
exports.app.use("/assets", express_1["default"].static(path_1["default"].join(__dirname, "../../public")));
exports.app.use(morgan_1["default"]("dev"));
Passport_1.configurePassport();
exports.app.get("/", function (req, res) { return res.redirect("/lobby.do"); });
exports.app.get("/login.do", UserController_1.getLogin);
exports.app.get("/register.do", UserController_1.getRegister);
exports.app.get("/lobby.do", UserService_1.isAuthenticated, RoomController_1.getLobby);
exports.app.get("/room.do", UserService_1.isAuthenticated, RoomController_1.getRoom);
exports.app.post("/login.rest", UserService_1.authenticate);
exports.app.post("/logout.rest", UserService_1.isAuthenticated, UserController_1.postLogout);
exports.app.post("/register.rest", UserController_1.postRegister);
exports.app.post("/room/create.rest", UserService_1.isAuthenticated, RoomController_1.postCreate);
exports.app.post("/room/addBalance.rest", UserService_1.isAuthenticated, RoomController_1.postAddBalance);
exports.app.post("/room/enter.rest", UserService_1.isAuthenticated, RoomController_1.postEnter);
exports.app.post("/room/leave.rest", UserService_1.isAuthenticated, RoomController_1.postLeave);
exports.app.post("/room/sit.rest", UserService_1.isAuthenticated, RoomController_1.postSit);
exports.app.post("/room/stand.rest", UserService_1.isAuthenticated, RoomController_1.postStand);
exports.app.post("/room/startRound.rest", UserService_1.isAuthenticated, RoomController_1.postStartRound);
exports.app.post("/room/bet.rest", UserService_1.isAuthenticated, RoomController_1.postBet);
//# sourceMappingURL=App.js.map